apiVersion: apps/v1
kind: Deployment
metadata:
  name: goclone-v1
  namespace: goclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goclone
      version: v1
  template:
    metadata:
      labels:
        app: goclone
        version: v1
    spec:
      containers:
        - name: goclone
          image: cppcyber/goclone:latest
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          imagePullPolicy: Always
          env:
            - name: VCENTER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: goclone-secret
                  key: username
            - name: VCENTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: goclone-secret
                  key: password
            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: goclone-secret
                  key: ldap_bind_password
          envFrom:
            - configMapRef:
                name: goclone-config
