apiVersion: v1
kind: Secret
metadata:
  name: goclone-secret
  namespace: goclone
type: Opaque
data:
  username: <base64 encoded username>
  password: <base64 encoded password>
  ldap_bind_password: <base64 encoded password>
